global:
  scrape_interval: 15s
  scrape_timeout: 5s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: apiservices
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'prometheus:9090'
        - 'myjournalapi:5050'
        - 'myjournalapi2:5050'
  - job_name: streams
    metrics
    
remote_write:
  - url: https://prometheus-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: 793630
      password: eyJrIjoiZjUxM2RhNzg5NzRhZjhjNThjNmUxZjgwNjYwN2E2ODk3MWNjNTU0NSIsIm4iOiJyZXRyb0FQSUtleSIsImlkIjo4MDMyNDV9

